import React, { useState } from "react";
import Navbar from "../others/navbar";
import {
  Search,
  User,
  Shield,
  Bell,
  MessageCircle,
  FileText,
  CreditCard,
  ChevronDown,
} from "lucide-react";

function Help() {
  const [open, setOpen] = useState(null);

 const faq = [
  {
    q: "How do I create an account?",
    a: "Click the Sign Up button, enter your details, verify your email address, and complete your profile. Once your account is created, you can explore all Market Rock features."
  },
  {
    q: "How do I logout?",
    a: "Open the More menu from the navigation bar and click the Logout button. Your account will be securely signed out from the current device."
  },
  {
    q: "How can I use Swing Stocks section ?",
    a: "The Swing Stocks highlights stocks that may be suitable for short- to medium-term trading opportunities. Use it to discover potential swing trade ideas, but always do your own research before making any investment decision."
  },
  {
    q: "What is Index Update?",
    a: "The Index Update section provides the latest movement of major market indices, including whether the market is trading higher or lower. It helps you quickly understand the overall market trend."
  },
  {
    q: "How can I use IPOs?",
    a: "Visit the IPO section to explore upcoming ipos. You can view important details such as opening and closing dates, issue price, listing information, and company overview. but always do your own research before making any investment decision"
  },
  {
  q: "What is Monthly Profits?",
  a: "The Monthly Profits page displays Market Rock's monthly performance. It provides a clear overview of the returns generated by our managed assets each month, allowing users to track performance, monitor growth, and review historical monthly profit reports."
  }
];

  const cards = [
    {
      icon: <User size={35} />,
      title: "Account",
      desc: "Profile, login & password",
    },
    {
      icon: <Shield size={35} />,
      title: "Security",
      desc: "Privacy & account safety",
    },
    {
      icon: <Bell size={35} />,
      title: "Notifications",
      desc: "Manage alerts",
    },
    {
      icon: <MessageCircle size={35} />,
      title: "Community",
      desc: "Posts & comments",
    },
    {
      icon: <CreditCard size={35} />,
      title: "Payments",
      desc: "Premium & billing",
    },
    {
      icon: <FileText size={35} />,
      title: "Policies",
      desc: "Terms & Privacy",
    },
  ];

  return (
    <>
      <Navbar />

   <div className="min-h-screen mt-20 ">
   {/* Hero */}
  <section className="px-5 -z-50 sm:px-16">
  <div className="relative overflow-hidden rounded-[40px] shape2 px-8 py-20 sm:px-16 shadow-lg">
    {/* Background Shapes */}
    <div className="absolute -top-20 -right-20 h-60 w-60 rounded-full bg-white/30"></div>
    <div className="absolute -bottom-24 -left-24 h-72 w-72 rounded-full bg-white/20"></div>
    <div className="relative z-10 text-center">
      <h1 className="text-5xl sm:text-7xl font-bold text-white mt-6">Help center</h1>
      <p className="text-white/90 mt-6 text-lg max-w-3xl mx-auto leading-8">
       find answers explore guides and get support
      </p>
    </div>
  </div>
</section>

 {/* Categories */}
 <section className="max-w-6xl mx-auto px-6 -mt-12">
   <div className="grid md:grid-cols-3 gap-6">
     {cards.map((item, index) => (
      <div
       key={index} className="bg-white rounded-3xl p-8 shadow-md hover:shadow-2xl hover:-translate-y-2 duration-300 cursor-pointer border z-50 border-transparent hover:border-green-300" >
            <div className="w-16 h-16 rounded-2xl bg-green-100 flex items-center justify-center text-green-600 mb-6">
             {item.icon}
            </div>
            <h2 className="font-bold text-xl">{item.title}</h2>
            <p className="text-gray-500 mt-2">{item.desc}</p>
      </div>
         ))}
    </div>
</section>

        {/* FAQ */}

<section className="max-w-5xl mx-auto px-6 py-20">
       <h2 className="text-4xl font-bold text-center mb-12">Frequently Asked Questions </h2>
        <div className="space-y-5">
         {faq.map((item, index) => (
            <div key={index} className="bg-white rounded-2xl shadow-md overflow-hidden" >
                <button onClick={() => setOpen(open === index ? null : index)
                } className="w-full flex justify-between items-center p-6">
                <span className="font-semibold text-lg">{item.q}</span>
                <ChevronDown className={`duration-300 ${ open === index ? "rotate-180" : "" }`}/>
                </button>{open === index && (
                <div className="px-6 pb-6 text-gray-600">{item.a}</div>
                 )}

            </div>
            ))}
        </div>

 </section>

{/* conatac */}
<section className="px-5 sm:px-16 py-20  text-center">
          <div className="shape2 rounded-3xl p-10">
            <h2 className="text-3xl font-bold text-white">If you have other problem contact with us </h2>
             <button className="h-10 cursor-pointer w-40 rounded-2xl shadow-md bg-white text-green-400 font-semibold text-[16px] mt-5">contact us</button>
          </div>
</section>
      </div>
    </>
  );
}

export default Help;