import React, { useState } from "react";
import Navbar from "../others/navbar";
import { Link } from "react-router-dom";
import { User, Shield, Bell, MessageCircle, FileText, CreditCard, ChevronDown } from "lucide-react";
import Footer from "../others/footer";

function Help() {
  const [open, setOpen] = useState(null);

  const faq = [
    {
      q: "How do I create an account?",
      a: "Click the Sign Up button, enter your details, verify your email address, and complete your profile. Once your account is created, you can explore all Market Rock features.",
    },
    {
      q: "How do I logout?",
      a: "Open the More menu from the navigation bar and click the Logout button. Your account will be securely signed out from the current device.",
    },
    {
      q: "How can I use Swing Stocks section?",
      a: "The Swing Stocks section highlights stocks that may be suitable for short- to medium-term trading opportunities. Use it to discover potential swing trade ideas, but always do your own research before making any investment decision.",
    },
    {
      q: "What is Index Update?",
      a: "The Index Update section provides the latest movement of major market indices, including whether the market is trading higher or lower. It helps you quickly understand the overall market trend.",
    },
    {
      q: "How can I use IPOs?",
      a: "Visit the IPO section to explore upcoming IPOs. You can view important details such as opening and closing dates, issue price, listing information, and company overview. Always do your own research before making any investment decision.",
    },
    {
      q: "What is Monthly Profits?",
      a: "The Monthly Profits page displays Market Rock's monthly performance. It provides an overview of the returns generated by our managed assets each month, allowing users to track performance, monitor growth, and review historical monthly profit reports.",
    },
  ];

  const cards = [
    { icon: <User size={30} />, title: "Account", desc: "Profile, login & password" },
    { icon: <Shield size={30} />, title: "Security", desc: "Privacy & account safety" },
    { icon: <Bell size={30} />, title: "Notifications", desc: "Manage alerts" },
    { icon: <MessageCircle size={30} />, title: "Community", desc: "Posts & comments" },
    { icon: <CreditCard size={30} />, title: "Payments", desc: "Premium & billing" },
    { icon: <FileText size={30} />, title: "Policies", desc: "Terms & Privacy" },
  ];

  return (
    <>
      <Navbar />

      <main className="min-h-screen bg-white dark:bg-[#0b0f0d] text-gray-900 dark:text-white transition-colors duration-300">

        {/* HERO */}
        <section className="px-4 sm:px-8 pt-24 pb-12">
          <div className="max-w-7xl mx-auto">
            <div className="rounded-3xl overflow-hidden shadow-md hover:shadow-xl transition duration-300 bg-white dark:bg-zinc-900 p-7 sm:p-12 md:p-16">
              <span className="inline-block bg-green-200 dark:bg-white text-emerald-600 dark:text-black font-semibold px-4 py-2 rounded-full text-xs sm:text-sm">
                MARKET ROCK SUPPORT
              </span>
              <h1 className="mt-6 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-extrabold leading-tight">
                Help Center
              </h1>

              <p className="mt-6 max-w-2xl text-gray-500 dark:text-white text-base leading-8">
                Find answers, explore Market Rock features, and get the support you need.
              </p>

            </div>
          </div>
        </section>


        {/* CATEGORIES */}
        <section className="max-w-6xl mx-auto px-4 sm:px-6 py-8">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">

            {cards.map((item, index) => (
              <div key={index} className="bg-gray-50 dark:bg-zinc-900 border border-gray-200 dark:border-white/10 rounded-3xl p-7 shadow-md hover:shadow-xl hover:-translate-y-1 duration-300 cursor-pointer hover:border-emerald-400 dark:hover:border-emerald-500">

                <div className="w-14 h-14 rounded-2xl bg-emerald-100 dark:bg-zinc-800 flex items-center justify-center text-emerald-500 dark:text-emerald-400 mb-5">
                  {item.icon}
                </div>

                <h2 className="font-bold text-xl">{item.title}</h2>

                <p className="text-gray-500 dark:text-gray-400 mt-2">
                  {item.desc}
                </p>

              </div>
            ))}

          </div>
        </section>


        {/* FAQ */}
        <section className="max-w-5xl mx-auto px-4 sm:px-6 py-20">

          <div className="text-center mb-12">

            <span className="text-emerald-500 dark:text-emerald-400 font-semibold text-sm">
              FAQ
            </span>

            <h2 className="font-bold text-3xl sm:text-4xl mt-3">
              Frequently Asked Questions
            </h2>

            <p className="text-gray-500 dark:text-gray-400 mt-4 max-w-2xl mx-auto">
              Find quick answers to common questions about Market Rock and its features.
            </p>

          </div>


          <div className="space-y-5">

            {faq.map((item, index) => (
              <div key={index} className="bg-gray-50 dark:bg-zinc-900 border border-gray-200 dark:border-white/10 rounded-2xl shadow-md hover:shadow-xl transition duration-300 overflow-hidden">

                <button onClick={() => setOpen(open === index ? null : index)} className="w-full flex justify-between items-center gap-5 p-5 sm:p-6 text-left cursor-pointer">

                  <span className="font-semibold text-base sm:text-lg">
                    {item.q}
                  </span>

                  <ChevronDown size={22} className={`flex-shrink-0 text-emerald-500 dark:text-emerald-400 transition-transform duration-300 ${open === index ? "rotate-180" : ""}`} />

                </button>

                {open === index && (
                  <div className="px-5 sm:px-6 pb-6 text-gray-600 dark:text-gray-400 leading-7">
                    {item.a}
                  </div>
                )}

              </div>
            ))}

          </div>

        </section>


        {/* CONTACT CTA */}
        <section className="px-4 sm:px-8 lg:px-16 pb-20">

          <div className="max-w-7xl mx-auto rounded-3xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-zinc-900 shadow-md hover:shadow-xl transition duration-300 p-8 sm:p-12 text-center">

            <div className="mx-auto h-14 w-14 rounded-full bg-emerald-100 dark:bg-zinc-800 flex items-center justify-center">
              <MessageCircle className="text-emerald-500 dark:text-emerald-400" size={25} />
            </div>

            <h2 className="text-2xl sm:text-3xl font-bold mt-5">
              Still need help?
            </h2>

            <p className="text-gray-500 dark:text-gray-400 mt-3 max-w-xl mx-auto">
              If you couldn't find the answer you're looking for, our team is here to help.
            </p>

            <Link to="/contact">
              <button className="mt-6 px-7 py-3 rounded-xl bg-emerald-500 text-white font-semibold hover:bg-emerald-600 transition cursor-pointer shadow-md">
                Contact Us
              </button>
            </Link>

          </div>

        </section>

      </main>

      <Footer />
    </>
  );
}

export default Help;